default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: "shore_development"

test:
  <<: *default
  database: "shore_test"

heroku:
  <<: *default
  database: "shore_heroku"

staging:
  <<: *default
  database: "shore_staging"

production:
  <<: *default
  database: "shore_production"
